#pragma once
#define HE_CPP_USE_STD_STRING 1
#define HE_CPP_USE_STD_VECTOR 1
#define HE_CPP_USE_STD_UNORDERED_MAP 1
#define HE_CPP_USE_EXCEPTIONS 0
#define HE_CPP_USE_RTTI 0
#define HE_CPP_COMPACT_NATIVE_EXCEPTION_MESSAGES 1
