const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const root = path.resolve(__dirname, '../../cs2.ts/.net.ts');
const ts = require(path.join(root, 'node_modules/typescript'));
require.extensions['.ts'] = (module, file) => module._compile(ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS } }).outputText, file);
const { Guid } = require(path.join(root, 'system/guid.ts'));
const { Random } = require(path.join(root, 'system/random.ts'));
const { TimeSpan } = require(path.join(root, 'system/time-span.ts'));
const { Environment } = require(path.join(root, 'system/environment.ts'));
const { NativeNumberUtil } = require(path.join(root, 'system/util/nat-number-util.ts'));
const { ArgumentGuard } = require(path.join(root, 'system/argument-guard.ts'));
const { ArgumentException } = require(path.join(root, 'system/argument.exception.ts'));
const { ArgumentNullException } = require(path.join(root, 'system/argument-null.exception.ts'));
require(path.join(root, 'system/convert.ts'));
require(path.join(root, 'system/util/nat-string-util.ts'));
test('scalar browser BCL members preserve generated contracts', () => {
    assert.equal(Guid.Empty.toString(), '00000000-0000-0000-0000-000000000000');
    const parsedGuid = { value: undefined };
    assert.equal(Guid.TryParse('00112233-4455-6677-8899-aabbccddeeff', parsedGuid), true);
    assert.equal(parsedGuid.value.toString(), '00112233-4455-6677-8899-aabbccddeeff');
    assert.equal(Guid.TryParse('00112233445566778899aabbccddeeff', parsedGuid), true);
    assert.equal(Guid.TryParse('{00112233-4455-6677-8899-aabbccddeeff}', parsedGuid), true);
    assert.equal(Guid.TryParse('(00112233-4455-6677-8899-aabbccddeeff)', parsedGuid), true);
    assert.equal(Guid.TryParse('not-a-guid', parsedGuid), false);
    assert.equal(parsedGuid.value.toString(), Guid.Empty.toString());
    assert.equal(Random.Shared, Random.Shared);
    assert.equal(typeof Random.Shared.NextDouble, 'function');
    assert.equal(Random.Shared.NextDouble() >= 0 && Random.Shared.NextDouble() < 1, true);
    assert.equal(TimeSpan.Zero.TotalMilliseconds, 0);
    const tickCount64 = Environment.TickCount64;
    assert.equal(typeof tickCount64, 'number');
    assert.equal(Environment.TickCount64 >= tickCount64, true);
    assert.equal(Boolean.TryParse(' TRUE ', { value: false }), true);
    const parsedNumber = { value: -1 };
    assert.equal(Number.TryParse('42', parsedNumber), true);
    assert.equal(parsedNumber.value, 42);
    assert.equal(Number.TryParse('-17', { value: 0 }, null, parsedNumber), true);
    assert.equal(parsedNumber.value, -17);
    assert.equal(Number.TryParse('12.5', parsedNumber), false);
    assert.equal(parsedNumber.value, 0);
    assert.equal(NativeNumberUtil.tryParseInteger('42', parsedNumber, -2147483648, 2147483647), true);
    assert.equal(parsedNumber.value, 42);
    assert.equal(NativeNumberUtil.tryParseInteger('12.5', parsedNumber, -2147483648, 2147483647), false);
    assert.equal(NativeNumberUtil.tryParseInteger('2147483648', parsedNumber, -2147483648, 2147483647), false);
    assert.equal(NativeNumberUtil.tryParseFloatingPoint('12.5', parsedNumber), true);
    assert.equal(parsedNumber.value, 12.5);
    assert.equal(NativeNumberUtil.tryParseFloatingPoint('1e3', parsedNumber), true);
    assert.equal(parsedNumber.value, 1000);
    assert.equal(NativeNumberUtil.tryParseFloatingPoint('not-a-number', parsedNumber), false);
    assert.equal(parsedNumber.value, 0);
    assert.equal(String.IsAsciiLetterOrDigit('A'), true);
    assert.equal(String.IsAsciiLetterOrDigit('_'), false);
    assert.equal(typeof ArgumentException.NullExceptionFactory, 'undefined');
    assert.equal(new ArgumentException('invalid value', 'value').Message, "invalid value (Parameter 'value')");
    assert.equal(new ArgumentNullException('value').Message, "Value cannot be null. (Parameter 'value')");
    assert.throws(() => ArgumentNullException.ThrowIfNull(null, 'request'), ArgumentNullException);
    assert.throws(() => ArgumentGuard.throwIfNullOrWhiteSpace(null, 'peerId'), ArgumentNullException);
    assert.throws(() => ArgumentGuard.throwIfNullOrWhiteSpace(' ', 'peerId'), ArgumentException);
});

test('Math.Clamp support retains .NET boundary and invalid-range behavior', () => {
    assert.equal(NativeNumberUtil.clamp(-1, 0, 2), 0);
    assert.equal(NativeNumberUtil.clamp(3, 0, 2), 2);
    assert.equal(NativeNumberUtil.clamp(1, 0, 2), 1);
    assert.equal(Object.is(NativeNumberUtil.clamp(-0, -1, 1), -0), true);
    assert.equal(Number.isNaN(NativeNumberUtil.clamp(NaN, 0, 1)), true);
    assert.throws(() => NativeNumberUtil.clamp(1, 2, 1), /min.*less than or equal/i);
});
